services:
  backend:
    build: ./tarot-backend
    env_file: ./tarot-backend/.env
    environment:
      - DATABASE_URL=sqlite:////data/backend_tarot.db
    volumes:
      - backend_data:/data
      - ./tarot-backend/static:/app/static:ro
    expose:
      - "8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  admin:
    build: ./tarot-admin-web
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/
    depends_on:
      - backend
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - admin
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  backend_data:

